In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
#Import the Pandas library and load the dataset.
df=pd.read_csv("/content/uncleaned_airline_dataset_20_columns (1).csv")
print(df)

         index   airline   flight source_city departure_time stops  \
0            0  SpiceJet  SG-8709       Delhi        Evening  zero
1            1  SpiceJet  SG-8157       Delhi  Early_Morning  zero
2            2   AirAsia   I5-764       Delhi  Early_Morning  zero
3            3   Vistara   UK-995       Delhi        Morning  zero
4            4   Vistara   UK-963       Delhi        Morning  zero
...        ...       ...      ...         ...            ...   ...
207823  207823   Vistara   UK-819       Delhi      Afternoon   one
207824  207824   Vistara   UK-819       Delhi      Afternoon   one
207825  207825   Vistara   UK-801       Delhi        Morning   one
207826  207826   Vistara   UK-807       Delhi          Night   one
207827  207827   Vistara   UK-801       Delhi        Morning   one

         arrival_time destination_city     class  duration  days_left  \
0               Night           Mumbai   Economy      2.17          1
1             Morning           Mumbai   Economy      2.33          1
2       Early_Morning           Mumbai   Economy      2.17          1
3           Afternoon           Mumbai   Economy      2.25          1
4             Morning           Mumbai   Economy      2.33          1
...               ...              ...       ...       ...        ...
207823          Night           Mumbai  Business      7.58         12
207824          Night           Mumbai  Business      9.17         12
207825          Night           Mumbai  Business     11.17         12
207826        Morning           Mumbai  Business     11.58         12
207827          Night           Mumbai  Business     11.67         12

          price  Passenger_Rating     Ticket_Type Meal_Option Baggage_kg  \
0        5953.0               5.0             NaN     Non-Veg       30kg
1        5953.0               4.0  Non-Refundable        NONE    unknown
2        5956.0               NaN  Non-Refundable     Non-Veg         25
3        5955.0               1.0             NaN         NaN       30kg
4        5955.0               4.0             NaN        NONE    unknown
...         ...               ...             ...         ...        ...
207823  53164.0               1.0  NON REFUNDABLE        veg         NaN
207824  53164.0               NaN  NON REFUNDABLE        NONE        NaN
207825  53164.0               4.0     refundable         NONE         25
207826  53164.0               4.0             NaN        veg     unknown
207827      NaN               NaN             NaN         NaN        NaN

       Checkin_Status Airport_Terminal Delay_Minutes Customer_ID
0         Not Checked               T2            30        C101
1          checked-in              NaN            10        C103
2            checked        terminal-2       unknown        C105
3                 NaN       terminal-2       unknown        C102
4          checked-in               T3           NaN        C101
...               ...              ...           ...         ...
207823     checked-in              NaN           NaN       C104
207824     checked-in              NaN           NaN        C102
207825     Checked-In       terminal-2           NaN       C104
207826            NaN               T1           15         C102
207827            NaN              NaN           NaN         NaN

[207828 rows x 20 columns]

In [ ]:
#Display the first 10 rows of the dataset.
df.head(10)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953.0,5.0,NaN,Non-Veg,30kg,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953.0,4.0,Non-Refundable,NONE,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956.0,NaN,Non-Refundable,Non-Veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955.0,1.0,NaN,NaN,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955.0,4.0,NaN,NONE,unknown,checked-in,T3,NaN,C101
5,5,Vistara,UK-945,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.33,1,5955.0,4.0,refundable,NaN,15,Checked-In,T2,0,C103
6,6,Vistara,UK-927,Delhi,Morning,zero,Morning,Mumbai,Economy,2.08,1,6060.0,4.0,refundable,veg,30kg,Not Checked,T2,5,C101
7,7,Vistara,UK-951,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.17,1,6060.0,4.0,NON REFUNDABLE,NONE,15,Not Checked,T2,NaN,NaN
8,8,GO_FIRST,G8-334,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5954.0,2.0,refundable,Veg,unknown,checked-in,T1,15,C104
9,9,GO_FIRST,G8-336,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5954.0,4.0,NON REFUNDABLE,Non-Veg,25,Not Checked,T1,unknown,C104

In [ ]:
#Display the last 10 rows of the dataset.
df.tail(10)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
207818,207818,Vistara,UK-817,Delhi,Evening,one,Night,Mumbai,Business,5.75,12,53164.0,2.0,NON REFUNDABLE,veg,NaN,checked,Terminal 1,10,C105
207819,207819,Vistara,UK-813,Delhi,Evening,one,Night,Mumbai,Business,5.83,12,53164.0,5.0,Refundable,veg,30kg,NaN,T1,unknown,C102
207820,207820,Vistara,UK-819,Delhi,Afternoon,one,Night,Mumbai,Business,6.00,12,53164.0,4.0,NaN,NONE,30kg,checked-in,T2,0,NaN
207821,207821,Vistara,UK-819,Delhi,Afternoon,one,Night,Mumbai,Business,6.50,12,53164.0,3.0,Non-Refundable,veg,20,checked-in,T1,unknown,C102
207822,207822,Vistara,UK-817,Delhi,Evening,one,Night,Mumbai,Business,7.33,12,53164.0,1.0,Refundable,veg,NaN,Checked-In,terminal-2,unknown,C102
207823,207823,Vistara,UK-819,Delhi,Afternoon,one,Night,Mumbai,Business,7.58,12,53164.0,1.0,NON REFUNDABLE,veg,NaN,checked-in,NaN,NaN,C104
207824,207824,Vistara,UK-819,Delhi,Afternoon,one,Night,Mumbai,Business,9.17,12,53164.0,NaN,NON REFUNDABLE,NONE,NaN,checked-in,NaN,NaN,C102
207825,207825,Vistara,UK-801,Delhi,Morning,one,Night,Mumbai,Business,11.17,12,53164.0,4.0,refundable,NONE,25,Checked-In,terminal-2,NaN,C104
207826,207826,Vistara,UK-807,Delhi,Night,one,Morning,Mumbai,Business,11.58,12,53164.0,4.0,NaN,veg,unknown,NaN,T1,15,C102
207827,207827,Vistara,UK-801,Delhi,Morning,one,Night,Mumbai,Business,11.67,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Find the total number of rows and columns in the dataset.
df.shape

(207828, 20)

In [ ]:
#Display the list of all column names.
df.columns

Index(['index', 'airline', 'flight', 'source_city', 'departure_time', 'stops',
       'arrival_time', 'destination_city', 'class', 'duration', 'days_left',
       'price', 'Passenger_Rating', 'Ticket_Type', 'Meal_Option', 'Baggage_kg',
       'Checkin_Status', 'Airport_Terminal', 'Delay_Minutes', 'Customer_ID'],
      dtype='object')

In [ ]:
#Display the data types of all columns.
df.dtypes

index                 int64
airline              object
flight               object
source_city          object
departure_time       object
stops                object
arrival_time         object
destination_city     object
class                object
duration            float64
days_left             int64
price               float64
Passenger_Rating    float64
Ticket_Type          object
Meal_Option          object
Baggage_kg           object
Checkin_Status       object
Airport_Terminal     object
Delay_Minutes        object
Customer_ID          object
dtype: object

In [ ]:
#Display basic statistical summary of the dataset.
df.describe()

,index,duration,days_left,price,Passenger_Rating
count,207828.00000,207828.000000,207828.000000,207827.000000,155783.000000
mean,103913.50000,11.554855,26.016177,6795.702267,3.172573
std,59994.92021,7.248123,13.569775,4878.259757,1.344071
min,0.00000,0.830000,1.000000,1105.000000,1.000000
25%,51956.75000,6.250000,15.000000,4177.000000,2.000000
50%,103913.50000,10.170000,26.000000,5798.000000,4.000000
75%,155870.25000,15.250000,38.000000,7803.000000,4.000000
max,207827.00000,49.830000,49.000000,95657.000000,5.000000

In [ ]:
import pandas as pd
df=pd.read_csv("/content/uncleaned_airline_dataset_20_columns (1) (1).csv")
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1.0,5953.0,5.0,NaN,Non-Veg,30kg,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1.0,5953.0,4.0,Non-Refundable,NONE,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1.0,5956.0,NaN,Non-Refundable,Non-Veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1.0,5955.0,1.0,NaN,NaN,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1.0,5955.0,4.0,NaN,NONE,unknown,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75809,75809,Air_India,AI-888,Mumbai,Evening,one,Morning,Hyderabad,Economy,15.50,39.0,4173.0,3.0,NaN,Veg,NaN,checked-in,terminal-2,30,C102
75810,75810,Air_India,AI-806,Mumbai,Early_Morning,one,Night,Hyderabad,Economy,15.58,39.0,4173.0,3.0,Non-Refundable,Veg,15,checked-in,T3,30,C105
75811,75811,Air_India,AI-635,Mumbai,Early_Morning,one,Night,Hyderabad,Economy,16.50,39.0,4173.0,3.0,NON REFUNDABLE,NaN,25,checked,T2,NaN,C104
75812,75812,Air_India,AI-660,Mumbai,Evening,one,Morning,Hyderabad,Economy,16.50,39.0,4173.0,2.0,NON REFUNDABLE,NaN,NaN,checked-in,terminal-2,NaN,NaN
75813,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Identify which columns contain missing values
df.isnull().sum()

index                   0
airline                 1
flight                  1
source_city             1
departure_time          1
stops                   1
arrival_time            1
destination_city        1
class                   1
duration                1
days_left               1
price                   1
Passenger_Rating    19062
Ticket_Type         15193
Meal_Option         15042
Baggage_kg          12489
Checkin_Status      14964
Airport_Terminal    12470
Delay_Minutes        9443
Customer_ID         12536
dtype: int64

In [ ]:
#Count the number of missing values in each column.
df.isnull().sum()

index                   0
airline                 1
flight                  1
source_city             1
departure_time          1
stops                   1
arrival_time            1
destination_city        1
class                   1
duration                1
days_left               1
price                   1
Passenger_Rating    19062
Ticket_Type         15193
Meal_Option         15042
Baggage_kg          12489
Checkin_Status      14964
Airport_Terminal    12470
Delay_Minutes        9443
Customer_ID         12536
dtype: int64

In [ ]:
df.nunique()

index               75813
airline                 6
flight                780
source_city             2
departure_time          6
stops                   3
arrival_time            6
destination_city        6
class                   1
duration              379
days_left              49
price                4449
Passenger_Rating        5
Ticket_Type             4
Meal_Option             4
Baggage_kg              5
Checkin_Status          4
Airport_Terminal        5
Delay_Minutes           7
Customer_ID             5
dtype: int64

In [ ]:
#Replace missing values in Passenger_Rating with the mean value
df["Passenger_Rating"].fillna(df["Passenger_Rating"].mean())

0        5.000000
1        4.000000
2        3.174355
3        1.000000
4        4.000000
           ...
75809    3.000000
75810    3.000000
75811    3.000000
75812    2.000000
75813    3.174355
Name: Passenger_Rating, Length: 75814, dtype: float64

In [ ]:
#Replace missing values in Meal_Option with "Unknown".
df['Meal_Option'].fillna("Unknown")

0        Non-Veg
1           NONE
2        Non-Veg
3        Unknown
4           NONE
          ...
75809        Veg
75810        Veg
75811    Unknown
75812    Unknown
75813    Unknown
Name: Meal_Option, Length: 75814, dtype: object

In [ ]:

import pandas as pd
df=pd.read_csv("/content/uncleaned_airline_dataset_20_columns (1) (1).csv")
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.0,NaN,Non-Veg,30kg,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.0,Non-Refundable,NONE,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,NaN,Non-Refundable,Non-Veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.0,NaN,NaN,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.0,NaN,NONE,unknown,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92522,92522,Vistara,UK-852,Bangalore,Morning,one,Evening,Delhi,Economy,10.25,42,4796,NaN,NaN,Veg,NaN,Not Checked,T3,60,C104
92523,92523,Vistara,UK-846,Bangalore,Morning,one,Evening,Delhi,Economy,11.25,42,4796,NaN,NON REFUNDABLE,NONE,25,checked-in,NaN,unknown,C105
92524,92524,Vistara,UK-866,Bangalore,Night,one,Morning,Delhi,Economy,12.00,42,4796,4.0,refundable,veg,30kg,NaN,terminal-2,0,C101
92525,92525,Vistara,UK-858,Bangalore,Early_Morning,one,Evening,Delhi,Economy,13.08,42,4796,NaN,refundable,veg,15,checked,T3,0,C101
92526,92526,SpiceJet,SG-768,Bangalore,Afternoon,one,Night,Delhi,Economy,5.50,42,56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Remove rows where Customer_ID is missing.
df = df.dropna(subset=['Customer_ID'])
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.0,NaN,Non-Veg,30kg,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.0,Non-Refundable,NONE,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,NaN,Non-Refundable,Non-Veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.0,NaN,NaN,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.0,NaN,NONE,unknown,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92521,92521,AirAsia,I5-1982,Bangalore,Early_Morning,one,Afternoon,Delhi,Economy,8.25,42,4570,3.0,refundable,veg,25,NaN,T2,5,C105
92522,92522,Vistara,UK-852,Bangalore,Morning,one,Evening,Delhi,Economy,10.25,42,4796,NaN,NaN,Veg,NaN,Not Checked,T3,60,C104
92523,92523,Vistara,UK-846,Bangalore,Morning,one,Evening,Delhi,Economy,11.25,42,4796,NaN,NON REFUNDABLE,NONE,25,checked-in,NaN,unknown,C105
92524,92524,Vistara,UK-866,Bangalore,Night,one,Morning,Delhi,Economy,12.00,42,4796,4.0,refundable,veg,30kg,NaN,terminal-2,0,C101
92525,92525,Vistara,UK-858,Bangalore,Early_Morning,one,Evening,Delhi,Economy,13.08,42,4796,NaN,refundable,veg,15,checked,T3,0,C101

In [ ]:
#Verify that missing values are handled.
df.isnull().sum()

index                   0
airline                 0
flight                  0
source_city             0
departure_time          0
stops                   0
arrival_time            0
destination_city        0
class                   0
duration                0
days_left               0
price                   0
Passenger_Rating    19407
Ticket_Type         15504
Meal_Option         15426
Baggage_kg          12675
Checkin_Status      15313
Airport_Terminal    12681
Delay_Minutes        9632
Customer_ID             0
dtype: int64

In [ ]:
#Remove leading and trailing spaces from all string columns.
df = df.apply(lambda col: col.str.strip() if col.dtype == 'object' else col)
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.0,NaN,Non-Veg,30kg,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.0,Non-Refundable,NONE,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,NaN,Non-Refundable,Non-Veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.0,NaN,NaN,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.0,NaN,NONE,unknown,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92521,92521,AirAsia,I5-1982,Bangalore,Early_Morning,one,Afternoon,Delhi,Economy,8.25,42,4570,3.0,refundable,veg,25,NaN,T2,5,C105
92522,92522,Vistara,UK-852,Bangalore,Morning,one,Evening,Delhi,Economy,10.25,42,4796,NaN,NaN,Veg,NaN,Not Checked,T3,60,C104
92523,92523,Vistara,UK-846,Bangalore,Morning,one,Evening,Delhi,Economy,11.25,42,4796,NaN,NON REFUNDABLE,NONE,25,checked-in,NaN,unknown,C105
92524,92524,Vistara,UK-866,Bangalore,Night,one,Morning,Delhi,Economy,12.00,42,4796,4.0,refundable,veg,30kg,NaN,terminal-2,0,C101
92525,92525,Vistara,UK-858,Bangalore,Early_Morning,one,Evening,Delhi,Economy,13.08,42,4796,NaN,refundable,veg,15,checked,T3,0,C101

In [ ]:
#Convert Meal_Option values to lowercase.
df['Meal_Option'] = df['Meal_Option'].str.lower()
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.0,NaN,non-veg,30kg,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.0,Non-Refundable,none,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,NaN,Non-Refundable,non-veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.0,NaN,NaN,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.0,NaN,none,unknown,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92521,92521,AirAsia,I5-1982,Bangalore,Early_Morning,one,Afternoon,Delhi,Economy,8.25,42,4570,3.0,refundable,veg,25,NaN,T2,5,C105
92522,92522,Vistara,UK-852,Bangalore,Morning,one,Evening,Delhi,Economy,10.25,42,4796,NaN,NaN,veg,NaN,Not Checked,T3,60,C104
92523,92523,Vistara,UK-846,Bangalore,Morning,one,Evening,Delhi,Economy,11.25,42,4796,NaN,NON REFUNDABLE,none,25,checked-in,NaN,unknown,C105
92524,92524,Vistara,UK-866,Bangalore,Night,one,Morning,Delhi,Economy,12.00,42,4796,4.0,refundable,veg,30kg,NaN,terminal-2,0,C101
92525,92525,Vistara,UK-858,Bangalore,Early_Morning,one,Evening,Delhi,Economy,13.08,42,4796,NaN,refundable,veg,15,checked,T3,0,C101

In [ ]:
#Convert Ticket_Type values to proper format (Refundable / Non-Refundable).
df['Ticket_Type'] = df['Ticket_Type'].str.strip().str.lower()

df['Ticket_Type'] = df['Ticket_Type'].replace({
    'refundable': 'Refundable',
    'non refundable': 'Non-Refundable',
    'non-refundable': 'Non-Refundable'
})
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.0,NaN,non-veg,30kg,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.0,Non-Refundable,none,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,NaN,Non-Refundable,non-veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.0,NaN,NaN,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.0,NaN,none,unknown,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92521,92521,AirAsia,I5-1982,Bangalore,Early_Morning,one,Afternoon,Delhi,Economy,8.25,42,4570,3.0,Refundable,veg,25,NaN,T2,5,C105
92522,92522,Vistara,UK-852,Bangalore,Morning,one,Evening,Delhi,Economy,10.25,42,4796,NaN,NaN,veg,NaN,Not Checked,T3,60,C104
92523,92523,Vistara,UK-846,Bangalore,Morning,one,Evening,Delhi,Economy,11.25,42,4796,NaN,Non-Refundable,none,25,checked-in,NaN,unknown,C105
92524,92524,Vistara,UK-866,Bangalore,Night,one,Morning,Delhi,Economy,12.00,42,4796,4.0,Refundable,veg,30kg,NaN,terminal-2,0,C101
92525,92525,Vistara,UK-858,Bangalore,Early_Morning,one,Evening,Delhi,Economy,13.08,42,4796,NaN,Refundable,veg,15,checked,T3,0,C101

In [ ]:
#Standardize Checkin_Status values.
df['Checkin_Status'] = df['Checkin_Status'].str.strip().str.lower()

df['Checkin_Status'] = df['Checkin_Status'].replace({
    'checked in': 'Checked-In',
    'check-in': 'Checked-In',
    'yes': 'Checked-In',
    'no': 'Not Checked-In',
    'not checked in': 'Not Checked-In'
})

df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.0,NaN,non-veg,30kg,not checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.0,Non-Refundable,none,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,NaN,Non-Refundable,non-veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.0,NaN,NaN,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.0,NaN,none,unknown,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92521,92521,AirAsia,I5-1982,Bangalore,Early_Morning,one,Afternoon,Delhi,Economy,8.25,42,4570,3.0,Refundable,veg,25,NaN,T2,5,C105
92522,92522,Vistara,UK-852,Bangalore,Morning,one,Evening,Delhi,Economy,10.25,42,4796,NaN,NaN,veg,NaN,not checked,T3,60,C104
92523,92523,Vistara,UK-846,Bangalore,Morning,one,Evening,Delhi,Economy,11.25,42,4796,NaN,Non-Refundable,none,25,checked-in,NaN,unknown,C105
92524,92524,Vistara,UK-866,Bangalore,Night,one,Morning,Delhi,Economy,12.00,42,4796,4.0,Refundable,veg,30kg,NaN,terminal-2,0,C101
92525,92525,Vistara,UK-858,Bangalore,Early_Morning,one,Evening,Delhi,Economy,13.08,42,4796,NaN,Refundable,veg,15,checked,T3,0,C101

In [ ]:
#Standardize Airport_Terminal values to T1, T2, T3 format.
df['Checkin_Status'] = df['Checkin_Status'].str.strip().str.lower()

df['Checkin_Status'] = df['Checkin_Status'].replace({
    'checked in': 'Checked-In',
    'check-in': 'Checked-In',
    'yes': 'Checked-In',
    'no': 'Not Checked-In',
    'not checked in': 'Not Checked-In'
})

df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.0,NaN,non-veg,30kg,not checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.0,Non-Refundable,none,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,NaN,Non-Refundable,non-veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.0,NaN,NaN,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.0,NaN,none,unknown,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92521,92521,AirAsia,I5-1982,Bangalore,Early_Morning,one,Afternoon,Delhi,Economy,8.25,42,4570,3.0,Refundable,veg,25,NaN,T2,5,C105
92522,92522,Vistara,UK-852,Bangalore,Morning,one,Evening,Delhi,Economy,10.25,42,4796,NaN,NaN,veg,NaN,not checked,T3,60,C104
92523,92523,Vistara,UK-846,Bangalore,Morning,one,Evening,Delhi,Economy,11.25,42,4796,NaN,Non-Refundable,none,25,checked-in,NaN,unknown,C105
92524,92524,Vistara,UK-866,Bangalore,Night,one,Morning,Delhi,Economy,12.00,42,4796,4.0,Refundable,veg,30kg,NaN,terminal-2,0,C101
92525,92525,Vistara,UK-858,Bangalore,Early_Morning,one,Evening,Delhi,Economy,13.08,42,4796,NaN,Refundable,veg,15,checked,T3,0,C101

In [ ]:
#Convert Passenger_Rating column to numeric datatype.
df['Passenger_Rating'] = pd.to_numeric(df['Passenger_Rating'])
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.0,NaN,non-veg,30kg,not checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.0,Non-Refundable,none,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,NaN,Non-Refundable,non-veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.0,NaN,NaN,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.0,NaN,none,unknown,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92521,92521,AirAsia,I5-1982,Bangalore,Early_Morning,one,Afternoon,Delhi,Economy,8.25,42,4570,3.0,Refundable,veg,25,NaN,T2,5,C105
92522,92522,Vistara,UK-852,Bangalore,Morning,one,Evening,Delhi,Economy,10.25,42,4796,NaN,NaN,veg,NaN,not checked,T3,60,C104
92523,92523,Vistara,UK-846,Bangalore,Morning,one,Evening,Delhi,Economy,11.25,42,4796,NaN,Non-Refundable,none,25,checked-in,NaN,unknown,C105
92524,92524,Vistara,UK-866,Bangalore,Night,one,Morning,Delhi,Economy,12.00,42,4796,4.0,Refundable,veg,30kg,NaN,terminal-2,0,C101
92525,92525,Vistara,UK-858,Bangalore,Early_Morning,one,Evening,Delhi,Economy,13.08,42,4796,NaN,Refundable,veg,15,checked,T3,0,C101

In [ ]:
#Convert Baggage_kg values by removing "kg" text.
df['Baggage_kg'] = df['Baggage_kg'].str.replace('kg', '', regex=False)
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.0,NaN,non-veg,30,not checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.0,Non-Refundable,none,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,NaN,Non-Refundable,non-veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.0,NaN,NaN,30,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.0,NaN,none,unknown,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92521,92521,AirAsia,I5-1982,Bangalore,Early_Morning,one,Afternoon,Delhi,Economy,8.25,42,4570,3.0,Refundable,veg,25,NaN,T2,5,C105
92522,92522,Vistara,UK-852,Bangalore,Morning,one,Evening,Delhi,Economy,10.25,42,4796,NaN,NaN,veg,NaN,not checked,T3,60,C104
92523,92523,Vistara,UK-846,Bangalore,Morning,one,Evening,Delhi,Economy,11.25,42,4796,NaN,Non-Refundable,none,25,checked-in,NaN,unknown,C105
92524,92524,Vistara,UK-866,Bangalore,Night,one,Morning,Delhi,Economy,12.00,42,4796,4.0,Refundable,veg,30,NaN,terminal-2,0,C101
92525,92525,Vistara,UK-858,Bangalore,Early_Morning,one,Evening,Delhi,Economy,13.08,42,4796,NaN,Refundable,veg,15,checked,T3,0,C101

In [ ]:
#Convert Delay_Minutes column into integer datatype.
df['Delay_Minutes'] = pd.to_numeric(df['Delay_Minutes'], errors='coerce').astype('Int64')
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.0,NaN,non-veg,30,not checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.0,Non-Refundable,none,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,NaN,Non-Refundable,non-veg,25,checked,terminal-2,<NA>,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.0,NaN,NaN,30,NaN,terminal-2,<NA>,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.0,NaN,none,unknown,checked-in,T3,<NA>,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92521,92521,AirAsia,I5-1982,Bangalore,Early_Morning,one,Afternoon,Delhi,Economy,8.25,42,4570,3.0,Refundable,veg,25,NaN,T2,5,C105
92522,92522,Vistara,UK-852,Bangalore,Morning,one,Evening,Delhi,Economy,10.25,42,4796,NaN,NaN,veg,NaN,not checked,T3,60,C104
92523,92523,Vistara,UK-846,Bangalore,Morning,one,Evening,Delhi,Economy,11.25,42,4796,NaN,Non-Refundable,none,25,checked-in,NaN,<NA>,C105
92524,92524,Vistara,UK-866,Bangalore,Night,one,Morning,Delhi,Economy,12.00,42,4796,4.0,Refundable,veg,30,NaN,terminal-2,0,C101
92525,92525,Vistara,UK-858,Bangalore,Early_Morning,one,Evening,Delhi,Economy,13.08,42,4796,NaN,Refundable,veg,15,checked,T3,0,C101

In [ ]:
# Replace "unknown" values with NaN.
import numpy as np
df.replace('unknown', np.nan, inplace=True)
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.0,NaN,non-veg,30,not checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.0,Non-Refundable,none,NaN,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,NaN,Non-Refundable,non-veg,25,checked,terminal-2,<NA>,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.0,NaN,NaN,30,NaN,terminal-2,<NA>,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.0,NaN,none,NaN,checked-in,T3,<NA>,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92521,92521,AirAsia,I5-1982,Bangalore,Early_Morning,one,Afternoon,Delhi,Economy,8.25,42,4570,3.0,Refundable,veg,25,NaN,T2,5,C105
92522,92522,Vistara,UK-852,Bangalore,Morning,one,Evening,Delhi,Economy,10.25,42,4796,NaN,NaN,veg,NaN,not checked,T3,60,C104
92523,92523,Vistara,UK-846,Bangalore,Morning,one,Evening,Delhi,Economy,11.25,42,4796,NaN,Non-Refundable,none,25,checked-in,NaN,<NA>,C105
92524,92524,Vistara,UK-866,Bangalore,Night,one,Morning,Delhi,Economy,12.00,42,4796,4.0,Refundable,veg,30,NaN,terminal-2,0,C101
92525,92525,Vistara,UK-858,Bangalore,Early_Morning,one,Evening,Delhi,Economy,13.08,42,4796,NaN,Refundable,veg,15,checked,T3,0,C101

In [ ]:
# Verify the updated data types.
df.dtypes

index                 int64
airline              object
flight               object
source_city          object
departure_time       object
stops                object
arrival_time         object
destination_city     object
class                object
duration            float64
days_left             int64
price                 int64
Passenger_Rating    float64
Ticket_Type          object
Meal_Option          object
Baggage_kg           object
Checkin_Status       object
Airport_Terminal     object
Delay_Minutes         Int64
Customer_ID          object
dtype: object

In [ ]:
# Check whether duplicate rows exist in the dataset.
df.duplicated().any()

np.False_

In [ ]:
 # Count the number of duplicate rows.
df.duplicated().sum()

np.int64(0)

In [ ]:
#Remove duplicate rows from the dataset.
df = df.drop_duplicates()
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.0,NaN,non-veg,30,not checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.0,Non-Refundable,none,NaN,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,NaN,Non-Refundable,non-veg,25,checked,terminal-2,<NA>,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.0,NaN,NaN,30,NaN,terminal-2,<NA>,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.0,NaN,none,NaN,checked-in,T3,<NA>,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92521,92521,AirAsia,I5-1982,Bangalore,Early_Morning,one,Afternoon,Delhi,Economy,8.25,42,4570,3.0,Refundable,veg,25,NaN,T2,5,C105
92522,92522,Vistara,UK-852,Bangalore,Morning,one,Evening,Delhi,Economy,10.25,42,4796,NaN,NaN,veg,NaN,not checked,T3,60,C104
92523,92523,Vistara,UK-846,Bangalore,Morning,one,Evening,Delhi,Economy,11.25,42,4796,NaN,Non-Refundable,none,25,checked-in,NaN,<NA>,C105
92524,92524,Vistara,UK-866,Bangalore,Night,one,Morning,Delhi,Economy,12.00,42,4796,4.0,Refundable,veg,30,NaN,terminal-2,0,C101
92525,92525,Vistara,UK-858,Bangalore,Early_Morning,one,Evening,Delhi,Economy,13.08,42,4796,NaN,Refundable,veg,15,checked,T3,0,C101

In [ ]:
# Find the total number of flights in the dataset.
len(df)

77337

In [ ]:
# Find the number of unique airlines.
df['airline'].nunique()

6

In [ ]:
# Display the list of unique source cities
df['source_city'].unique()

array(['Delhi', 'Mumbai', 'Bangalore'], dtype=object)

In [ ]:
#Display the list of unique destination cities.
df['destination_city'].unique()

array(['Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai', 'Delhi'],
      dtype=object)

In [ ]:
# Count flights for each airline
df['airline'].value_counts()

airline
Vistara      23055
Air_India    18605
Indigo       14628
GO_FIRST     10420
AirAsia       6538
SpiceJet      4091
Name: count, dtype: int64

In [ ]:
# Find the average ticket price.
df['price'].mean()

np.float64(6329.033528582697)

In [ ]:
df.columns

Index(['index', 'airline', 'flight', 'source_city', 'departure_time', 'stops',
       'arrival_time', 'destination_city', 'class', 'duration', 'days_left',
       'price', 'Passenger_Rating', 'Ticket_Type', 'Meal_Option', 'Baggage_kg',
       'Checkin_Status', 'Airport_Terminal', 'Delay_Minutes', 'Customer_ID'],
      dtype='object')

In [ ]:
# Find the maximum ticket price
df['price'].max()

35145

In [ ]:
# Find the minimum ticket price.
df['price'].min()

1890

In [ ]:
# Find the average ticket price for each airline.
df.groupby('airline')['price'].mean()

airline
AirAsia      4398.500918
Air_India    6936.138457
GO_FIRST     5599.572265
Indigo       5492.930681
SpiceJet     6239.992911
Vistara      7262.557666
Name: price, dtype: float64

In [ ]:
# Display the top 5 most expensive flights
df.nlargest(5,'price')

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
35512,35512,Air_India,AI-877,Delhi,Morning,two_or_more,Early_Morning,Chennai,Economy,20.33,2,35145,NaN,NaN,non-veg,NaN,not checked,T1,15,C104
54112,54112,Air_India,AI-611,Mumbai,Morning,one,Afternoon,Bangalore,Economy,25.67,9,34188,3.0,Refundable,veg,25,not checked,NaN,30,C104
84305,84305,SpiceJet,SG-768,Bangalore,Afternoon,one,Morning,Delhi,Economy,19.58,2,34158,2.0,Non-Refundable,veg,NaN,not checked,Terminal 1,<NA>,C104
37448,37448,Air_India,AI-485,Delhi,Early_Morning,one,Morning,Chennai,Economy,29.50,16,33613,5.0,NaN,none,30,checked,terminal-2,10,C103
78638,78638,Vistara,UK-841,Mumbai,Morning,two_or_more,Night,Chennai,Economy,11.33,11,33401,4.0,Non-Refundable,veg,NaN,NaN,T1,<NA>,C104

In [ ]:
# Find the number of flights from each source city.
df['source_city'].value_counts()

source_city
Delhi        35969
Mumbai       34277
Bangalore     7091
Name: count, dtype: int64

In [ ]:
# Find the number of flights to each destination city.
df['destination_city'].value_counts()

destination_city
Bangalore    15753
Delhi        15222
Kolkata      14582
Chennai      12085
Hyderabad    11379
Mumbai        8316
Name: count, dtype: int64

In [ ]:
df.columns

Index(['index', 'airline', 'flight', 'source_city', 'departure_time', 'stops',
       'arrival_time', 'destination_city', 'class', 'duration', 'days_left',
       'price', 'Passenger_Rating', 'Ticket_Type', 'Meal_Option', 'Baggage_kg',
       'Checkin_Status', 'Airport_Terminal', 'Delay_Minutes', 'Customer_ID'],
      dtype='object')

In [ ]:
# Identify the source city with the most flights.
df['source_city'].value_counts().idxmax()

'Delhi'

In [ ]:
# Find the average ticket price for each source city.
df.groupby('source_city')['price'].mean()

source_city
Bangalore    6437.651248
Delhi        6278.437821
Mumbai       6359.656650
Name: price, dtype: float64

In [ ]:
# Count flights based on number of stops.
df['stops'].value_counts()

stops
one            61155
zero           12241
two_or_more     3941
Name: count, dtype: int64

In [ ]:
# Find the average price based on flight class.
df.groupby('flight')['price'].mean()

flight
6.00E-128    6798.000000
6.00E-136    4702.557377
6.00E-138    2875.800000
6.00E-148    4546.266667
6.00E-152    8043.294737
                ...
UK-988       7029.944649
UK-993       6128.057377
UK-994       7176.789981
UK-995       6675.435208
UK-996       6968.560878
Name: price, Length: 935, dtype: float64

In [ ]:
df.columns

Index(['index', 'airline', 'flight', 'source_city', 'departure_time', 'stops',
       'arrival_time', 'destination_city', 'class', 'duration', 'days_left',
       'price', 'Passenger_Rating', 'Ticket_Type', 'Meal_Option', 'Baggage_kg',
       'Checkin_Status', 'Airport_Terminal', 'Delay_Minutes', 'Customer_ID'],
      dtype='object')

In [ ]:
# Find the airline with the highest average passenger rating.
df.groupby('airline')['Passenger_Rating'].mean().idxmax()

'SpiceJet'

In [ ]:
# Count flights based on departure time.
df['departure_time'].value_counts()

departure_time
Evening          18548
Early_Morning    18030
Morning          16569
Afternoon        13930
Night             9662
Late_Night         598
Name: count, dtype: int64

In [ ]:
# Find the average delay minutes of flights
df['Delay_Minutes'].mean()

np.float64(20.06595396154841)

In [ ]:
# Display flights delayed more than 30 minutes
df[df['Delay_Minutes'] > 30]

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
12,12,Indigo,6E-5001,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5955,5.0,Non-Refundable,non-veg,NaN,NaN,T2,60,C101
28,28,SpiceJet,SG-8169,Delhi,Evening,zero,Night,Mumbai,Economy,2.33,1,10260,NaN,Non-Refundable,non-veg,30,checked,T3,60,C105
33,33,Vistara,UK-817,Delhi,Evening,one,Morning,Mumbai,Economy,16.17,1,12150,1.0,Non-Refundable,veg,15,NaN,T2,60,C103
34,34,Vistara,UK-819,Delhi,Afternoon,one,Morning,Mumbai,Economy,18.00,1,12150,4.0,Refundable,veg,30,checked,NaN,60,C102
37,37,Air_India,AI-453,Delhi,Early_Morning,one,Afternoon,Mumbai,Economy,8.83,1,11900,4.0,NaN,veg,15,checked-in,T1,60,C105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92487,92487,Air_India,AI-640,Bangalore,Early_Morning,one,Night,Delhi,Economy,13.67,42,4294,2.0,NaN,non-veg,20,checked-in,terminal-2,60,C103
92507,92507,Indigo,6E-2174,Bangalore,Evening,zero,Night,Delhi,Economy,2.92,42,4500,2.0,Non-Refundable,NaN,15,checked,T1,60,C102
92511,92511,Indigo,6E-2186,Bangalore,Early_Morning,zero,Morning,Delhi,Economy,3.00,42,4500,5.0,Refundable,veg,30,checked-in,T1,60,C101
92519,92519,Vistara,UK-818,Bangalore,Evening,zero,Night,Delhi,Economy,2.75,42,4502,1.0,Non-Refundable,NaN,NaN,not checked,Terminal 1,60,C103
92522,92522,Vistara,UK-852,Bangalore,Morning,one,Evening,Delhi,Economy,10.25,42,4796,NaN,NaN,veg,NaN,not checked,T3,60,C104

In [ ]:
#Save the cleaned dataset as clean_airline_dataset.csv.
df.to_csv('clean_airline_dataset.csv', index=False)
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.0,NaN,non-veg,30,not checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.0,Non-Refundable,none,NaN,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,NaN,Non-Refundable,non-veg,25,checked,terminal-2,<NA>,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.0,NaN,NaN,30,NaN,terminal-2,<NA>,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.0,NaN,none,NaN,checked-in,T3,<NA>,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92521,92521,AirAsia,I5-1982,Bangalore,Early_Morning,one,Afternoon,Delhi,Economy,8.25,42,4570,3.0,Refundable,veg,25,NaN,T2,5,C105
92522,92522,Vistara,UK-852,Bangalore,Morning,one,Evening,Delhi,Economy,10.25,42,4796,NaN,NaN,veg,NaN,not checked,T3,60,C104
92523,92523,Vistara,UK-846,Bangalore,Morning,one,Evening,Delhi,Economy,11.25,42,4796,NaN,Non-Refundable,none,25,checked-in,NaN,<NA>,C105
92524,92524,Vistara,UK-866,Bangalore,Night,one,Morning,Delhi,Economy,12.00,42,4796,4.0,Refundable,veg,30,NaN,terminal-2,0,C101
92525,92525,Vistara,UK-858,Bangalore,Early_Morning,one,Evening,Delhi,Economy,13.08,42,4796,NaN,Refundable,veg,15,checked,T3,0,C101

In [ ]:
# Display the final shape of the cleaned dataset.
df.shape

(77337, 20)